name: Deploy main Updates

on:
  push:
    branches:
      - main #Déclenchement uniquement sur la branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Upload des fichiers via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: sftp.ca-node-23.katabump.com
          username: 855145634737684492.4cf6034e
          password: 6702af62dd96a
          port: 2022
          uploads: |
            ./ => /

      - name: 🔄 Création du fichier restart.txt
        run: touch restart.txt # Crée un fichier vide en local

      - name: 🔄 Redémarrage du bot
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: sftp.ca-node-23.katabump.com
          username: 855145634737684492.4cf6034e
          password: 6702af62dd96a
          port: 2022
          uploads: |
            restart.txt => /restart.txt
