name: Deploy main Updates

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Upload des fichiers via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{secrets.SFTP_USER}}
          password: ${{secrets.SFTP_PASS}}
          port: 2022
          uploads: |
            ./ => /

      - name: 🔄 Création du fichier restart.txt
        run: touch restart.txt

      - name: 🔄 Redémarrage du bot
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{secrets.SFTP_USER}}
          password: ${{secrets.SFTP_PASS}}
          port: 2022
          uploads: |
            restart.txt => /restart.txt
