name: Deploy via SFTP

on:
  push:
    branches:
      - main # Déploiement automatique sur push dans la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22 # Vérifie le port SFTP utilisé par ton hébergeur
          source: "." # Envoie tous les fichiers du repo
          target: "/chemin/vers/ton/bot" # Remplace par le bon chemin sur ton hébergeur
          strip_components: 1

      - name: Restart Bot (if possible)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          script: |
            touch /restart.txt
