name: Tests and Quality Checks

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: false

      - name: Check code formatting
        run: npm run format:check
        continue-on-error: false

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Test build/startup
        run: |
          timeout 30s npm start || code=$?
          if [[ $code -ne 124 && $code -ne 0 ]]; then
            echo "❌ Le bot a crashé au démarrage"
            exit 1
          fi
          echo "✅ Le bot démarre correctement"

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true
